### ISSUE TITLE
Move DAI report from Repositories Portal to the HEAL Stewards Guidance portal

### ISSUE THREAD

**Issue by aubrieweyhmiller1** [heal-data-stewards/website#44]
Hi,

The resource ["DAI report"](https://drive.google.com/file/d/1hFe3vm0GC_olMnKLC-DhqD90oG3QMMt6/view?pli=1) should be moved from the [Repositories portal](https://www.healdatafair.org/resources/repositories) to the [HEAL Stewards Guidance portal.](https://www.healdatafair.org/resources/heal-stewards-guidance).

**Comment by scrummish** [comment]
completed
